name: "Read/Write profiles' data"
on: [push]

jobs:
  table:
    runs-on: ubuntu-latest
    name: Update README from json data
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          persist-credentials: false
          fetch-depth: 0
      - name: Read/Write data into README
        uses: neontuts/gh-actions-markdown-link-generator@main
        with:
          json-file-path: "Data.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          object-field-names: '[ "name", "username" ]'
          file-to-use: "_layouts/sidebar.md"
          html-cell: "- [{{ name }}](../journeys/{{ username }}.md)"
